<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QP399I7" failures="1" tests="9" name="tests2.TestAddProducts2" time="117.686" errors="0" timestamp="2019-11-28T15:46:33 IST" skipped="0">
  <testcase classname="tests2.TestAddProducts2" name="testAddNewProductWindowAppearTC71" time="29.404"/>
  <testcase classname="tests2.TestAddProducts2" name="testEditProductWindowAppearTC72" time="3.427"/>
  <testcase classname="tests2.TestAddProducts2" name="testValidationAppearWithoutEnteringDetailsTC73" time="3.228"/>
  <testcase classname="tests2.TestAddProducts2" name="testValidationAppearOnEnteringPartialDetailsAndHitSubmitbuttonTC74" time="4.343"/>
  <testcase classname="tests2.TestAddProducts2" name="testNewProductIsAddedTC75" time="14.644"/>
  <testcase classname="tests2.TestAddProducts2" name="testDataIsSavedInAllTheFieldsOfAddedProductTC76" time="24.594"/>
  <testcase classname="tests2.TestAddProducts2" name="testProductIsEditedTC77" time="6.545">
    <failure message="did not expect to find [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at tests2.TestAddProducts2.testProductIsEditedTC77(TestAddProducts2.java:308)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testProductIsEditedTC77 -->
  <testcase classname="tests2.TestAddProducts2" name="testAllTheDetailsAreFetchedOnOpeningNewAddedProductOnOrderScreenTC78" time="19.369"/>
  <testcase classname="tests2.TestAddProducts2" name="testAllTheDetailsAreFetchedOnOpeningNewAddedProductOnShipmentsScreenTC79" time="12.132"/>
</testsuite> <!-- tests2.TestAddProducts2 -->
